# Imagen base oficial de Python
FROM python:3.11-slim

# Crear carpeta de trabajo
WORKDIR /app

# Copiar archivos
COPY requirements.txt requirements.txt
COPY src/ src/
COPY models/ models/
COPY data/ data/

# Instalar dependencias
RUN pip install --upgrade pip && \
    pip install -r requirements.txt

# Exponer puerto para streamlit
EXPOSE 8501

# Streamlit inicia vía docker-compose
